channels:
  - defaults
dependencies:
  - python=3.9
  - pip
  - numpy
  - conda-forge::psycopg2==2.9
  - tqdm==4.63
  - plotly::plotly==5.7.0
  - conda-forge::sqlalchemy>=1.4.37
  - conda-forge::geopandas==0.10
  - h5py=3.6
  - conda-forge::shapely==1.8
  - pip:
    - geoalchemy2~=0.12.0
    - diskcache~=5.4.0
    - psutil~=5.9.0
    - dash[diskcache]~=2.4.0
    - dash-bootstrap-components~=1.1.0
    - plyfile~=0.7.4
    - hydra-core~=1.1.1
    - dash-vtk~=0.0.9
    - vtk~=9.1.0
