hydra:
  run:
    dir: .
  output_subdir: null

defaults:
  - db: local
  - _self_

data:
  filepath: ./data/Carola_PointCloud.ply

loader:
 _target_: loader.ply_loader.PLYColorLoader

drop_db: true

data_splitting:
  voxel_size: 2
  chunk_size: 2_000_000

  